pip install discord
pip install colorama 
pip install requestes
pip install discord.py
pip install numpy
pip install requests
pip install aiohttp
pip install bs4
pip install ymongo
pip install selenium
pip install pyPrivnote
pip install pybase64
pip install numpy
pip install smtplib
pip install functools
pip install logging
pip install random
pip install io
pip install datime
pip install codecs
pip install gtts
pip install dnspython
pip install urllib.parse
pip install ctypes
pip install string
pip install sys
pip install json
pip install webbrowser
pip install re
pip install urllib.request
pip install notify-py
pip install image
pip install asyncio
pip install functools 
pip install termcolor